{"name": "test_eval[6*9-42]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 54 == 42\n  +54\n  -42", "trace": "test_input = '6*9', expected = 42\n\n    @pytest.mark.parametrize(\"test_input,expected\", [\n        (\"3+5\", 8),\n        (\"2+4\", 6),\n        (\"6*9\", 42),\n    ])\n    def test_eval(test_input, expected):\n        print(test_input, expected)\n>       assert eval(test_input) == expected\nE       assert 54 == 42\nE         +54\nE         -42\n\ntest.py:11: AssertionError"}, "parameters": [{"name": "test_input", "value": "'6*9'"}, {"name": "expected", "value": "42"}], "start": 1586622201813, "stop": 1586622201813, "uuid": "459f1e78-5136-4d73-9446-e0a07201d727", "historyId": "9ba1545e057316b0e4083d2a8ac6fe75", "testCaseId": "bf1b9329ab92b43c31a1ebfbde33da90", "fullName": "allure.test#test_eval", "labels": [{"name": "parentSuite", "value": "allure"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "35332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure.test"}]}