Traceback (most recent call last):
  File "e:/Work/Project/Python/Learn/exception/BaseException.py", line 5, in <module>
    a = 3/0
ZeroDivisionError: division by zero
