{
  "uid" : "2319fa45542edcec",
  "name" : "test_case[case1]",
  "fullName" : "scripts.test_case.Test_case#test_case",
  "historyId" : "2267bb04dfeab26bec94c39d05e91380",
  "time" : {
    "start" : 1586763618887,
    "stop" : 1586763618887,
    "duration" : 0
  },
  "description" : "  执行断言 ",
  "descriptionHtml" : "<p>执行断言</p>\n",
  "status" : "broken",
  "statusMessage" : "KeyError: 'case_expect'",
  "statusTrace" : "self = <uti.RequestHandler.RequestHandler object at 0x11111d090>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    def __init__(self, case):\n        self.case = case\n        try:\n>           self.case_expect = json.loads(self.case['case_expect'])\nE           KeyError: 'case_expect'\n\nuti/RequestHandler.py:21: KeyError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_case.Test_case object at 0x11108a590>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    @pytest.mark.parametrize('case', ExcelHandler().get_excel_data)\n    def test_case(self, case):\n        \"\"\"  执行断言 \"\"\"\n        # print(case)\n        # 发请求\n>       response = RequestHandler(case).get_response\n\nscripts/test_case.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <uti.RequestHandler.RequestHandler object at 0x11111d090>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    def __init__(self, case):\n        self.case = case\n        try:\n            self.case_expect = json.loads(self.case['case_expect'])\n        except:\n>           self.case_expect = self.case['case_expect']\nE           KeyError: 'case_expect'\n\nuti/RequestHandler.py:23: KeyError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_Class__pytest_setup_class",
    "time" : {
      "start" : 1586763618784,
      "stop" : 1586763618784,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "  执行断言 ",
    "status" : "broken",
    "statusMessage" : "KeyError: 'case_expect'",
    "statusTrace" : "self = <uti.RequestHandler.RequestHandler object at 0x11111d090>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    def __init__(self, case):\n        self.case = case\n        try:\n>           self.case_expect = json.loads(self.case['case_expect'])\nE           KeyError: 'case_expect'\n\nuti/RequestHandler.py:21: KeyError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_case.Test_case object at 0x11108a590>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    @pytest.mark.parametrize('case', ExcelHandler().get_excel_data)\n    def test_case(self, case):\n        \"\"\"  执行断言 \"\"\"\n        # print(case)\n        # 发请求\n>       response = RequestHandler(case).get_response\n\nscripts/test_case.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <uti.RequestHandler.RequestHandler object at 0x11111d090>\ncase = {'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'id': 'asc-0003', 'isRun': 'RUN', 'message': '', ...}\n\n    def __init__(self, case):\n        self.case = case\n        try:\n            self.case_expect = json.loads(self.case['case_expect'])\n        except:\n>           self.case_expect = self.case['case_expect']\nE           KeyError: 'case_expect'\n\nuti/RequestHandler.py:23: KeyError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "f9050eb2863f5100",
      "name" : "log",
      "source" : "f9050eb2863f5100.txt",
      "type" : "text/plain",
      "size" : 79
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "_Class__pytest_setup_class::0",
    "time" : {
      "start" : 1586763618895,
      "stop" : 1586763625107,
      "duration" : 6212
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "scripts"
  }, {
    "name" : "suite",
    "value" : "test_case"
  }, {
    "name" : "subSuite",
    "value" : "Test_case"
  }, {
    "name" : "host",
    "value" : "localhost"
  }, {
    "name" : "thread",
    "value" : "58663-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "scripts.test_case"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "{'id': 'asc-0003', 'module': 'flask', 'url': '127.0.0.1:8888/login?name=yuhang&pw=999', 'isRun': 'RUN', 'method': 'POST', 'params': '{}', 'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'result': '', 'message': ''}"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "2319fa45542edcec.json",
  "parameterValues" : [ "{'id': 'asc-0003', 'module': 'flask', 'url': '127.0.0.1:8888/login?name=yuhang&pw=999', 'isRun': 'RUN', 'method': 'POST', 'params': '{}', 'expect': '{\"code\": 201, \"message\": \"登录成功\"}', 'result': '', 'message': ''}" ]
}