{
  "uid" : "b4d4d10835fdc041",
  "name" : "test_case[case3]",
  "fullName" : "scripts.test_case.Test_case#test_case",
  "historyId" : "7e828afbaedfa893de205d6534b52ff9",
  "time" : {
    "start" : 1586449153320,
    "stop" : 1586449153321,
    "duration" : 1
  },
  "description" : "  执行断言 ",
  "descriptionHtml" : "<p>执行断言</p>\n",
  "status" : "broken",
  "statusMessage" : "KeyError: 'case_project'",
  "statusTrace" : "self = <scripts.test_case.Test_case object at 0x10b085e90>\ncase = {'expect': '{\"code\": 202, \"message\": \"登录成功\"}', 'id': 'asc-0004', 'isRun': 'RUN', 'message': '', ...}\n\n    @pytest.mark.parametrize('case', ExcelHandler().get_excel_data)\n    def test_case(self, case):\n        \"\"\"  执行断言 \"\"\"\n        # print(case)\n        # 发请求\n        response = RequestHandler(case).get_response\n    \n        # 制作 allure 报告\n>       allure.dynamic.title(case['case_project'])\nE       KeyError: 'case_project'\n\nscripts/test_case.py:29: KeyError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_Class__pytest_setup_class",
    "time" : {
      "start" : 1586449153189,
      "stop" : 1586449153189,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "description" : "  执行断言 ",
    "status" : "broken",
    "statusMessage" : "KeyError: 'case_project'",
    "statusTrace" : "self = <scripts.test_case.Test_case object at 0x10b085e90>\ncase = {'expect': '{\"code\": 202, \"message\": \"登录成功\"}', 'id': 'asc-0004', 'isRun': 'RUN', 'message': '', ...}\n\n    @pytest.mark.parametrize('case', ExcelHandler().get_excel_data)\n    def test_case(self, case):\n        \"\"\"  执行断言 \"\"\"\n        # print(case)\n        # 发请求\n        response = RequestHandler(case).get_response\n    \n        # 制作 allure 报告\n>       allure.dynamic.title(case['case_project'])\nE       KeyError: 'case_project'\n\nscripts/test_case.py:29: KeyError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "cd8c00aec4f2b316",
      "name" : "log",
      "source" : "cd8c00aec4f2b316.txt",
      "type" : "text/plain",
      "size" : 200
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "_Class__pytest_setup_class::0",
    "time" : {
      "start" : 1586449153327,
      "stop" : 1586449170169,
      "duration" : 16842
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "scripts"
  }, {
    "name" : "suite",
    "value" : "test_case"
  }, {
    "name" : "subSuite",
    "value" : "Test_case"
  }, {
    "name" : "host",
    "value" : "localhost"
  }, {
    "name" : "thread",
    "value" : "10306-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "scripts.test_case"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "{'id': 'asc-0004', 'module': 'flask', 'url': 'name=yuhang&pw=111', 'isRun': 'RUN', 'method': 'GET', 'parameter': '', 'expect': '{\"code\": 202, \"message\": \"登录成功\"}', 'result': '', 'message': ''}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "777cd0faaa0f7363",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '/Users/sonic/Project/Python/Pytest/logs/2020-04-09.log'",
      "time" : {
        "start" : 1586446922269,
        "stop" : 1586446922270,
        "duration" : 1
      }
    }, {
      "uid" : "57fcebc0c5b7d572",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '/Users/sonic/Project/Python/Pytest/logs/2020-04-09.log'",
      "time" : {
        "start" : 1586446302767,
        "stop" : 1586446302767,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "b4d4d10835fdc041.json",
  "parameterValues" : [ "{'id': 'asc-0004', 'module': 'flask', 'url': 'name=yuhang&pw=111', 'isRun': 'RUN', 'method': 'GET', 'parameter': '', 'expect': '{\"code\": 202, \"message\": \"登录成功\"}', 'result': '', 'message': ''}" ]
}